apiVersion: v1
kind: Service
metadata:
  name: inquiry-webapi-service
  namespace: fiap-contacts
spec:
  type: LoadBalancer
  selector:
    app: inquiry-webapi
  ports:
    - port: 82
      targetPort: 8081
