apiVersion: v1
kind: Service
metadata:
  name: inquiry-webapi-service
spec:
  type: LoadBalancer  # Ou NodePort, dependendo do ambiente
  selector:
    app: inquiry-webapi
  ports:
    - port: 82
      targetPort: 8081
