apiVersion: v1
kind: Service
metadata:
  name: inquiry-webapi-service
  namespace: fiap-contacts
  labels:     
    monitored: "true"
spec:
  type: LoadBalancer
  selector:
    app: inquiry-webapi
  ports:
    - name: metrics
      port: 82
      targetPort: 8081
