apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-application
  labels:
    app: registration-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registration-application
  template:
    metadata:
      labels:
        app: registration-application
    spec:
      containers:
        - name: registration-application
          image: registration-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: OTHER_SERVICE_URL
              value: "http://other-service:5002"