apiVersion: v1
kind: Service
metadata:
  name: registration-webapi-service
spec:
  type: LoadBalancer  # Ou NodePort, dependendo do ambiente
  selector:
    app: registration-webapi
  ports:
    - port: 80
      targetPort: 80
