apiVersion: v1
kind: Service
metadata:
  name: registration-webapi-service
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer  # Ou NodePort, dependendo do ambiente
  selector:
    app: registration-webapi
  ports:
    - name: metrics
      port: 81
      targetPort: 8081
