apiVersion: v1
kind: Service
metadata:
  name: registration-webapi-service
  namespace: fiap-contacts
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer
  selector:
    app: registration-webapi
  ports:
    - name: metrics
      port: 81
      targetPort: 8081
