apiVersion: v1
kind: Service
metadata:
  name: registration-webapi-service
  namespace: fiap-contacts
spec:
  type: LoadBalancer
  selector:
    app: registration-webapi
  ports:
    - port: 81
      targetPort: 8081
