apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=  # Base64 encoded "admin"
  admin-password: YWRtaW4=  # Base64 encoded "admin"
