apiVersion: v1
kind: Service
metadata:
  name: modification-webapi-service
  namespace: fiap-contacts
spec:
  type: LoadBalancer
  selector:
    app: modification-webapi
  ports:
    - port: 83
      targetPort: 8081
