apiVersion: v1
kind: Service
metadata:
  name: modification-webapi-service
spec:
  type: LoadBalancer  # Ou NodePort, dependendo do ambiente
  selector:
    app: modification-webapi
  ports:
    - port: 80
      targetPort: 80
