apiVersion: v1
kind: Service
metadata:
  name: modification-webapi-service
  namespace: fiap-contacts
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer
  selector:
    app: modification-webapi
  ports:
    - name: metrics
      port: 83
      targetPort: 8081
