apiVersion: apps/v1
kind: Deployment
metadata:
  name: modification-webapi
  labels:
    app: modification-webapi
spec:
  replicas: 3  # Número de réplicas desejadas
  selector:
    matchLabels:
      app: modification-webapi
  template:
    metadata:
      labels:
        app: modification-webapi
    spec:
      containers:
      - name: modification-webapi
        image: modification-service:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        env:
        - name: MODIFICATION_APP_URL
          value: "http://modification-application-service:5001"