apiVersion: v1
kind: Service
metadata:
  name: termination-webapi-service
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer  # Ou NodePort, dependendo do ambiente
  selector:
    app: termination-webapi
  ports:
    - name: metrics
      port: 84
      targetPort: 8081
