apiVersion: v1
kind: Service
metadata:
  name: termination-webapi-service
  namespace: fiap-contacts
  labels:     
    monitored: "true"  
spec:
  type: LoadBalancer
  selector:
    app: termination-webapi
  ports:
    - name: metrics
      port: 84
      targetPort: 8081
