apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-management
  namespace: fiap-contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-management-service
  template:
    metadata:
      labels:
        app: database-management-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
        
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;']
          
      containers:
        - name: database-management-service
          image: database-management-service:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: webapi-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: webapi-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: services-secret
                  key: RABBITMQ_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: webapi-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: services-secret
                  key: CONNECTION_STRING