apiVersion: v1
kind: Service
metadata:
  name: database-management-service
  namespace: fiap-contacts
spec:
  selector:
    app: database-management-service
  ports:
    - port: 90
      targetPort: 8666
